### PR TITLE
Upgrade emotion to v10

### PR DESCRIPTION
**Pull request by teddybradford**
This PR upgrades emotion from v9 to the latest v10.

### CODE REVIEW

**Comment by patrickgordon** [comment]
Hi there, thanks for the PR! I'll check this out next couple of days

**Comment by ntnbrtnkv** [comment]
Hello, any progress?

**Comment by patrickgordon** [comment]
Sorry for the delay. I will look at this tomorrow

**Comment by patrickgordon** [comment]
Thank you for your contribution @teddybradford. I'll publish a new version to NPM soon

**Pull request merged**
